# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik_posilkow', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nazwisko',
            field=models.CharField(default='nazwisko', max_length=200),
            preserve_default=False,
        ),
    ]
