# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik_posilkow', '0003_book_nazwisko'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ilosc',
            field=models.CharField(default='100g', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.IntegerField(),
        ),
    ]
