# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-24 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik_posilkow', '0004_auto_20170521_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='person',
        ),
    ]
