# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-24 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik_posilkow', '0007_auto_20170524_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='kalorie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='produkt',
        ),
        migrations.RenameField(
            model_name='zawodnik',
            old_name='pages',
            new_name='wiek',
        ),
    ]
