# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-25 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik_posilkow', '0008_auto_20170524_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Posilek',
        ),
    ]
